server {
    server_name bafbordeaux.fr www.bafbordeaux.fr;

    root /opt/baf;
    index index.html;

    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/bafbordeaux.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bafbordeaux.fr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    keepalive_timeout 65;

    location ~* \.(php|env|git|htaccess|htpasswd)$ {
        deny all;
        return 404;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 30s;
        proxy_connect_timeout 10s;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name bafbordeaux.fr www.bafbordeaux.fr;

    location /.well-known/acme-challenge/ {
        root /opt/baf;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
